Lesson 3
SashaVasal/fefu_backend_3_6 pull request #10
Opened 2022-05-06 09:06 UTC by SashaVasal

Lesson 3: Add news (api & web) and pages (api)

2022-05-11 14:04 UTC, chrn-feip commented
@tonighty ждём предыдущего ДЗ и ребейза

2022-05-13 04:20 UTC, chrn-feip commented
@SashaVasal сделайте ребейз ветки.
@tonighty можно смотреть

2022-05-15 08:07 UTC, tonighty requested changes
Не хватает апи для страниц (с документацией)

2022-05-17 07:42 UTC, tonighty approved these changes

2022-05-17 07:43 UTC, merged