Lesson 5
SashaVasal/fefu_backend_3_6 pull request #12
Opened 2022-05-06 09:07 UTC by SashaVasal

Lesson 5: Add auth (web & api)

2022-05-11 14:13 UTC, chrn-feip commented
@tonighty ждём предыдущего ДЗ и ребейза

2022-05-15 08:20 UTC, tonighty requested changes
Хватает апи для аутентификации

2022-05-17 07:53 UTC, tonighty requested changes

2022-05-17 07:53 UTC, tonighty commented on merch-shop/app/Http/Controllers/Api/AuthController.php
> +            $request->session()->regenerate();
в апи вход должен быть по токену (см. laravel sanctum)

2022-05-18 22:04 UTC, closed without merging