Lesson 4: Add appeal form (web & api)
SashaVasal/fefu_backend_3_6 pull request #15
Opened 2022-05-18 22:04 UTC by SashaVasal

(cherry picked from commit 907691c50cee41832ffd4d8fd7914cc9f59a7c4d)

2022-05-19 00:32 UTC, chrn-feip requested changes
Не трогайте старый миграции. Вот вообще никак: ни код внутри, ни название. Вы (или предполагаемый участник команды разработки) не сможете её откатить потом, потому что в таблицу migrations она записалась со старым именем, когда была применена.

2022-05-19 00:32 UTC, chrn-feip commented on merch-shop/app/Http/Controllers/Api/AppealController.php
> +        $appeal->phone = PhoneSanitizer::sanitize($data['phone']);
В API запросе может отсутствовать атрибут телефона или почты, предусмотрите  null для таких случаев:
PhoneSanitizer::sanitize($data['phone'] ?? null)

2022-05-19 00:32 UTC, chrn-feip commented on merch-shop/app/Http/Controllers/Api/AppealController.php
> +        $appeal->email = $data['email'];
Тут аналогично

2022-05-19 00:32 UTC, chrn-feip commented on merch-shop/app/Http/Controllers/Web/AppealController.php
> +        return view('appeal',['success'=>session('success',true)]);
Здесь success явно true. Его надо в сессию положить и сделать редирект на форму.

2022-05-19 00:32 UTC, chrn-feip commented on merch-shop/app/Http/Requests/AppealFormRequest.php
> +            'email' => ['string','nullable','email'],
email:rfc

2022-05-19 00:32 UTC, chrn-feip commented on merch-shop/resources/views/Page.blade.php
> -<!DOCTYPE html>
Это почему меняется в данном ДЗи почему удаляется?

2022-05-19 00:32 UTC, chrn-feip commented on merch-shop/app/Http/Controllers/Api/AppealController.php
> +    #[OpenApi\Operation]
А тег вам не понадобился для отображения документации? А метод POST почему не уточнили?

2022-05-20 02:28 UTC, SashaVasal commented on merch-shop/resources/views/Page.blade.php
> -<!DOCTYPE html>
Вроде в старых коммитов я создавал блейды с заглавными буквами. В этом решил удалить

2022-05-20 05:56 UTC, chrn-feip requested changes

2022-05-20 05:56 UTC, chrn-feip commented on merch-shop/app/Http/Controllers/Api/AppealController.php
>          $appeal->email = $data['email'];
С почтой аналогично

2022-05-20 05:56 UTC, chrn-feip commented on merch-shop/app/Http/Controllers/Web/AppealController.php
> +        $appeal->phone = PhoneSanitizer::sanitize($data['phone'] ?? null);
Для веба не нужно, у вас там на форме есть поле для почты, вы его даже пустым, но отправите. А в API нет гарантий, что его передадут и валидатор не поругается, т.к, оно необязательное. А при попытке взять значение и несуществующему ключу из массива будет ошибка.

2022-05-20 05:59 UTC, chrn-feip commented on merch-shop/resources/views/Page.blade.php
> -<!DOCTYPE html>
А со строчными буквами шаблон при этом остался?

2022-05-21 00:28 UTC, SashaVasal commented on merch-shop/resources/views/Page.blade.php
> -<!DOCTYPE html>
да

2022-05-21 08:15 UTC, merged